# 로컬 설정
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mariadb://localhost:3306/lezhin_clone?rewriteBatchedStatements=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: new1234!
    hikari:
      maximum-pool-size: 1
  jwt:
    secret: 01QXUr9HbyVBN5HSqKMfLPhBy4oxefXVqec86NZ5HHc= # 최소 32글자
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        '[format_sql]': true
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
      springframework:
        security: DEBUG # 스프링 시큐리티 로그
