# 상용 설정
server:
  port: 80
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://webtoon-clone.chmm4a0oib9n.ap-northeast-2.rds.amazonaws.com:3306/webtoon_clone?rewriteBatchedStatements=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mo!1034419
    hikari:
      maximum-pool-size: 1
  jwt:
    secret: 01QXUr9HbyVBN5HSqKMfLPhBy4oxefXVqec86NZ5HHc= # 최소 32글자
  jpa:
    hibernate:
      ddl-auto: validate