server:
  port: 8081
  servlet:
    context-path: /api
spring:
  jpa:
    open-in-view: false # true = Transaction 바깥에서도 영속성 유지
    properties:
      hibernate:
        # globally_quoted_identifiers: true # sql의 예약어를 변수로 설정해도 오류가 발생하지 않도록 백틱(`)으로 감싸줌
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 1000 # sql 구문을 1000 단위로 일괄적으로 처리
        order_inserts: true
        order_updates: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: c36da6ee7856df1298cf383304245259 # 앱키 -> REST API 키
            client-secret: IFpxMTDaA6uLfWDWtRLmvJHPJQgOmJEI # 카카오 로그인 -> 보안 -> Client Secret 코드
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-name: Kakao
          naver:
            client-id: GizOs1Uwg0gIdYqG8Rdf # Client ID
            client-secret: JMBRH0iE2L # Client Secret
            authorization-grant-type: authorization_code
            scope: # 
              - name
              - profile_image
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            client-name: Naver
          google:
            client-id: 530020897697-27nrefopgdlhom4j89svj6dmbe85dc9p.apps.googleusercontent.com # 클라이언트 ID
            client-secret: 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 # 클라이언트 보안 비밀번호
            authorization-grant-type: authorization_code
            scope: # 
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-name: Google
          github:
            client-id: Iv23linTJfSWTn6vwvXC # 클라이언트 ID
            # client-id: Ov23lir64zrElhVwdPye # 클라이언트 ID
            client-secret: 1d0caf8df754579832751e15cb3964b3af9d972d # 클라이언트 보안 비밀번호
            # client-secret: 9334d722ab811af810081763d3de0c3847b90ac4 # 클라이언트 보안 비밀번호
            authorization-grant-type: authorization_code
            scope: # 
              - avatar_url
              - email
              - name
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: Github
            
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # "인가 코드 받기" 항목
            token-uri: https://kauth.kakao.com/oauth/token # "토큰 받기" 항목
            user-info-uri: https://kapi.kakao.com/v2/user/me # "사용자 정보 가져오기" 항목
            user-info-authentication-method: header
            user-name-attribute: id # 식별자
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # "인가 코드 받기" 항목
            token-uri: https://nid.naver.com/oauth2.0/token # "토큰 받기" 항목
            user-info-uri: https://openapi.naver.com/v1/nid/me # "사용자 정보 가져오기" 항목
            user-info-authentication-method: header
            user-name-attribute: response # 식별자
  cache:
    type: redis
  google:
    client-id: 530020897697-27nrefopgdlhom4j89svj6dmbe85dc9p.apps.googleusercontent.com
    client-secret: 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
    refresh-token: 1//04LKd2JycC849CgYIARAAGAQSNwF-L9IrVCseUqpS1LwQ4do3V1kjZYcbJL-XXZwprqaV9tyA0Jv1aFfDs7Len6bGyqnXMOHjQ8Y
    from-email: ahtkdtn@gmail.com
