server:
  port: 8081
  servlet:
    context-path: /api
spring:
  jpa:
    open-in-view: false # true = Transaction 바깥에서도 영속성 유지
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 1000 # sql 구문을 1000 단위로 일괄적으로 처리
        order_inserts: true
        order_updates: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: c36da6ee7856df1298cf383304245259 # 앱키 -> REST API 키
            client-secret: IFpxMTDaA6uLfWDWtRLmvJHPJQgOmJEI # 카카오 로그인 -> 보안 -> Client Secret 코드
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # "인가 코드 받기" 항목
            token-uri: https://kauth.kakao.com/oauth/token # "토큰 받기" 항목
            user-info-uri: https://kapi.kakao.com/v2/user/me # "사용자 정보 가져오기" 항목
            user-info-authentication-method: header
            user-name-attribute: id # 식별자