# 로컬 설정
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mariadb://localhost:3306/lezhin_clone?rewriteBatchedStatements=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: new1234!
    hikari:
      maximum-pool-size: 1
  jwt:
    secret: 01QXUr9HbyVBN5HSqKMfLPhBy4oxefXVqec86NZ5HHc= # 최소 32글자
  jpa:
    hibernate:
      ddl-auto: validate