# 상용 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://webtoon-clone.chmm4a0oib9n.ap-northeast-2.rds.amazonaws.com:3306/webtoon_clone?rewriteBatchedStatements=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${{secrets.PROD_MARIADB_USERNAME}}
    password: mo!1034419
    hikari:
      maximum-pool-size: 1
  jwt:
    secret: 01QXUr9HbyVBN5HSqKMfLPhBy4oxefXVqec86NZ5HHc= # 최소 32글자
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "http://mosworld.kr/api/login/oauth2/code/kakao"
          naver:
            redirect-uri: "http://mosworld.kr/api/login/oauth2/code/naver"
          google:
            redirect-uri: "http://mosworld.kr/api/login/oauth2/code/google"
          github:
            client-id: Ov23lin09L2WLb93lEQI
            client-secret: 9bbadf9450fa1b26e10269d3ec1a132664199e57
            redirect-uri: "http://mosworld.kr/api/login/oauth2/code/github"
            
  data:
    redis:
      host: webtoon-clone-redis.kxrrtr.ng.0001.apn2.cache.amazonaws.com
      port: 6379
